#! /bin/sh

# ffmpeg -s 1920x1080 -framerate 30 -f x11grab -i :0.0+0,0 -f pulse -ac 2 -i 0 $1
ffmpeg -s 1920x1080 -hwaccel cuvid -f x11grab -i :0.0 -f pulse -ac 2 -i 0 -vf select=concatdec_select -c:v h264_nvenc -b:v 16M $1
