#! /bin/sh

if [ $# -gt 0 ]
then
    mpv https://twitch.tv/$1
else
    selected=$(dmenu -l 20 -m 0 -p "Streamer:" < ~/twitch.txt)

    if [ "$selected" = "" ]
    then
        exit
    fi

    mpv https://twitch.tv/${selected}
fi

