#! /bin/sh

txtn=$(tput sgr0)
txtr=$(tput setaf 1)

if [ $# -gt 0 ]
then
    NAME=$1
    lc=$(youtube-dl https://twitch.tv/${NAME} --skip-download 2>&1 | grep "offline" | wc -l)

    if [ "$lc" = "0" ]
    then
        echo "${NAME} is online"
    else
        echo "${txtr}${NAME} is offline${txtn}"
    fi
else
    while IFS='' read -r LINE || [ -n "${LINE}" ]; do
        lc=$(youtube-dl https://twitch.tv/${LINE} --skip-download 2>&1 | grep "offline" | wc -l)

        if [ "$lc" = "0" ]
        then
            echo "${LINE} is online"
        else
            echo "${txtr}${LINE} is offline${txtn}"
        fi
    done < ~/twitch.txt
fi

